version: '3'

services:

  frontend:
    build:
      context: newcombin
      dockerfile: Dockerfile
    container_name: quiron_frontend
    ports: 
      - "8080:8080"
    volumes: 
      - .:/home/node/app:rw
    restart: "no"
    command: /bin/sh -c "yarn && cd newcombin && quasar dev"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
